[package]
name = "tinycc"
version = "1.0.0"
authors = ["iTitou"]
description = "Compiler for the Tiny language"
build = "build.rs"


[build-dependencies]
lalrpop = "0.12.5"

[dependencies]
lalrpop-util = "0.12.5"
regex = "0.2"
